### ISSUE TITLE
Error using  idp authentication sin simplesaml

### ISSUE THREAD

**Issue by eldie1984** [pdias/SamlBundle#5]
When i configure the simplesaml to authenticate against another simplesaml and configure the synfony apliction to use this sp, after login succefully on the second simplesaml i get the error 

"SimpleSAML_Error_NoState: NOSTATE
Backtrace:
2 /var/www/simplesamlphp/lib/SimpleSAML/Auth/State.php:225 (SimpleSAML_Auth_State::loadState)
1 /var/www/simplesamlphp/modules/saml/www/sp/saml2-acs.php:63 (require)
0 /var/www/simplesamlphp/www/module.php:134 (N/A)"

But if i test the authenticaction in the first simplesaml i can login succesfully in the second simplesaml and obtain all the parameters.

After using the first simplesaml authentication test the simfony application get the attributes correctly al login the user

**Comment by pdias** [comment]
Hello. 

I'm not understand well.  You can post the config?

**Comment by eldie1984** [comment]
first simplesaml ip 192.168.57.77

config/authsources.php

<?php

    $config = array(

    'default-sp' => array(
            'saml:SP',

            'idp' => 'http://192.168.64.230/simplesaml/saml2/idp/metadata.php',
            'RelayState' => 'http://192.168.64.230/pruebasaml',

        ),

    );


metadata/saml20-id-remote.php

    $metadata['http://192.168.64.230/simplesaml/saml2/idp/metadata.php'] = array (
      'entityid' => 'http://192.168.64.230/simplesaml/saml2/idp/metadata.php',
      'contacts' => 
      array (
      ),
      'metadata-set' => 'saml20-idp-remote',
      'SingleSignOnService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => 'http://192.168.64.230/simplesaml/saml2/idp/SSOService.php',
        ),
      ),
      'SingleLogoutService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => 'http://192.168.64.230/simplesaml/saml2/idp/SingleLogoutService.php',
        ),
      ),
      'ArtifactResolutionService' => 
      array (
      ),
      'keys' => 
      array (
        0 => 
        array (
          'encryption' => false,
          'signing' => true,
          'type' => 'X509Certificate',
          'X509Certificate' => '
    MIIDXTCCAkWgAwIBAgIJAIxDC6bo3rq/MA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwHhcNMTUwO
    DA0MTcyMDE4WhcNMjUwODAzMTcyMDE4WjBFMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ
    8AMIIBCgKCAQEAv4PyTBXj3ao3xIiQVTS/qvLL7XfdEqqqTaIYIaJ+W+iLXjh5eUJuNc6ju3ls45UAIvPXRwd6On6Wh+MBNK+0sv17jp4AkIhz72cNyUAYoIhDuq74WSl47ld9Ni6yo5Q0AQcZ2fIPii921jR
    55wsjwYm1UpyU3x6/QwtwKO7qDSsbusznSwTuE/yFoMi5RUR9IQtE+1vi+kwspw+D6Sq6J11+SJ+bjADHrLzTTF9Gr2hZu3eWJEcSzKE9+5jyK+dyYZmPbqfZeNKtDiBe7RfkGBUw+JkOCYqBmKJIAEQfQr4b
    cYYlb4wNXMVqzr5QbE8V1OA87TKFCX2e/GmWSskC9wIDAQABo1AwTjAdBgNVHQ4EFgQUy2t6rzImsc40gmDWM/gufTwsNp8wHwYDVR0jBBgwFoAUy2t6rzImsc40gmDWM/gufTwsNp8wDAYDVR0TBAUwAwEB/
    zANBgkqhkiG9w0BAQsFAAOCAQEAaErR/9jRh9Q2ToBzoNdVB5UFLM8uJxaLhccWoe0X0lbXD5cfoGsjKrFFaSNUu8N0K7cXO777ueQvtuamjMkX8aFMDnPNAPXN2M3erOys6kcHHft0BtjfaTxHgTjAsa9aYD
    GvJGm2Wm9xG4c59Ii4UEc/AasP9ieax1sKdwBnYiOlTGgB5550/7vEl/oXhcIoRNbB/syQjf+XoCA1ezEIGVoGyMHyebTim3Bcl8g23hdRSQwO28yuvfzmiR24Mg863//aan126lC6QCRFLFqygi6GskmluwD
    /qUGDFXYYvibnpHL0FiMemfkzNdhZLsPC3f+7YD+Thm+Lp83gozgSDQ==
    ',
        ),
        1 => 
        array (
          'encryption' => true,
          'signing' => false,
          'type' => 'X509Certificate',
          'X509Certificate' => '
    MIIDXTCCAkWgAwIBAgIJAIxDC6bo3rq/MA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNVBAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBXaWRnaXRzIFB0eSBMdGQwHhcNMTUwO
    DA0MTcyMDE4WhcNMjUwODAzMTcyMDE4WjBFMQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ
    8AMIIBCgKCAQEAv4PyTBXj3ao3xIiQVTS/qvLL7XfdEqqqTaIYIaJ+W+iLXjh5eUJuNc6ju3ls45UAIvPXRwd6On6Wh+MBNK+0sv17jp4AkIhz72cNyUAYoIhDuq74WSl47ld9Ni6yo5Q0AQcZ2fIPii921jR
    55wsjwYm1UpyU3x6/QwtwKO7qDSsbusznSwTuE/yFoMi5RUR9IQtE+1vi+kwspw+D6Sq6J11+SJ+bjADHrLzTTF9Gr2hZu3eWJEcSzKE9+5jyK+dyYZmPbqfZeNKtDiBe7RfkGBUw+JkOCYqBmKJIAEQfQr4b
    cYYlb4wNXMVqzr5QbE8V1OA87TKFCX2e/GmWSskC9wIDAQABo1AwTjAdBgNVHQ4EFgQUy2t6rzImsc40gmDWM/gufTwsNp8wHwYDVR0jBBgwFoAUy2t6rzImsc40gmDWM/gufTwsNp8wDAYDVR0TBAUwAwEB/
    zANBgkqhkiG9w0BAQsFAAOCAQEAaErR/9jRh9Q2ToBzoNdVB5UFLM8uJxaLhccWoe0X0lbXD5cfoGsjKrFFaSNUu8N0K7cXO777ueQvtuamjMkX8aFMDnPNAPXN2M3erOys6kcHHft0BtjfaTxHgTjAsa9aYD
    GvJGm2Wm9xG4c59Ii4UEc/AasP9ieax1sKdwBnYiOlTGgB5550/7vEl/oXhcIoRNbB/syQjf+XoCA1ezEIGVoGyMHyebTim3Bcl8g23hdRSQwO28yuvfzmiR24Mg863//aan126lC6QCRFLFqygi6GskmluwD
    /qUGDFXYYvibnpHL0FiMemfkzNdhZLsPC3f+7YD+Thm+Lp83gozgSDQ==
    ',
        ),
      ),
    );




second simplesaml ip 192.168.64.230

config/authsources.php

    <?php

    $config = array(

        'user-login' => array(
            'exampleauth:UserPass',
            'dac:dac' => array(
                'uid' => array('dac'),
                'eduPersonAffiliation' => array('member', 'dac'),
            ),
            'user:userpass' => array(
                'uid' => array('user'),
                'eduPersonAffiliation' => array('member', 'user'),
            ),
        ),

    );


metadata/saml20-idp-hosted.php



    <?php
    /**
     * SAML 2.0 IdP configuration for simpleSAMLphp.
     *
     * See: https://simplesamlphp.org/docs/stable/simplesamlphp-reference-idp-hosted
     */

    $metadata['__DYNAMIC:1__'] = array(
            /*
             * The hostname of the server (VHOST) that will use this SAML entity.
             * 
             * Can be '__DEFAULT__', to use this entry by default.
             */
            'host' => '__DEFAULT__',

            /* X.509 key and certificate. Relative to the cert directory. */
            'privatekey' => 'prueba.pem', 
            'certificate' => 'prueba.crt',

            /*
             * Authentication source to use. Must be one that is configured in
             * 'config/authsources.php'.
             */
            'auth' => 'user-login',

            /*
             * WARNING: SHA-1 is disallowed starting January the 1st, 2014.
             * 
             * Uncomment the following option to start using SHA-256 for your signatures.
             * Currently, simpleSAMLphp defaults to SHA-1, which has been deprecated since
             * 2011, and will be disallowed by NIST as of 2014. Please refer to the following
             * document for more information:
             * 
             * http://csrc.nist.gov/publications/nistpubs/800-131A/sp800-131A.pdf
             * 
             * If you are uncertain about service providers supporting SHA-256 or other
             * algorithms of the SHA-2 family, you can configure it individually in the
             * SP-remote metadata set for those that support it. Once you are certain that
             * all your configured SPs support SHA-2, you can safely remove the configuration
             * options in the SP-remote metadata set and uncomment the following option.
             * 
             * Please refer to the IdP hosted reference for more information.
             */
            //'signature.algorithm' => 'http://www.w3.org/2001/04/xmldsig-more#rsa-sha256',

            /* Uncomment the following to use the uri NameFormat on attributes. */
            /* 
            'attributes.NameFormat' => 'urn:oasis:names:tc:SAML:2.0:attrname-format:uri',
            'authproc' => array(
                    // Convert LDAP names to oids.
                    100 => array('class' => 'core:AttributeMap', 'name2oid'),
            ),
            */

            /*
             * Uncomment the following to specify the registration information in the
             * exported metadata. Refer to:
         * http://docs.oasis-open.org/security/saml/Post2.0/saml-metadata-rpi/v1.0/cs01/saml-metadata-rpi-v1.0-cs01.html
             * for more information.
             */
            /*
    'RegistrationInfo' => array(
                    'authority' => 'urn:mace:example.org',
                    'instant' => '2008-01-17T11:28:03Z',
                    'policies' => array(
                            'en' => 'http://example.org/policy',
                            'es' => 'http://example.org/politica',
                    ),
            ),
            */
    );


metadata/saml20-sp-remote.php

    <?php
    /**
     * SAML 2.0 remote SP metadata for simpleSAMLphp.
     *
     * See: https://simplesamlphp.org/docs/stable/simplesamlphp-reference-sp-remote
     */

    /*
     * Example simpleSAMLphp SAML 2.0 SP
     */
    $metadata['https://saml2sp.example.org'] = array(
      'AssertionConsumerService' => 'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-acs.php/default-sp',
      'SingleLogoutService' => 'https://saml2sp.example.org/simplesaml/module.php/saml/sp/saml2-logout.php/default-sp',
    );

    /*
     * This example shows an example config that works with Google Apps for education.
     * What is important is that you have an attribute in your IdP that maps to the local part of the email address
     * at Google Apps. In example, if your google account is foo.com, and you have a user that has an email john@foo.com, then you
     * must set the simplesaml.nameidattribute to be the name of an attribute that for this user has the value of 'john'.
     */
    $metadata['google.com'] = array(
      'AssertionConsumerService' => 'https://www.google.com/a/g.feide.no/acs',
      'NameIDFormat' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress',
      'simplesaml.nameidattribute' => 'uid',
      'simplesaml.attributes' => FALSE,
    );
    $metadata['http://192.168.57.77:81'] = array (
      'entityid' => 'http://192.168.57.77:81',
      'contacts' => 
      array (
      ),
      'metadata-set' => 'saml20-sp-remote',
      'AssertionConsumerService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
          'Location' => 'http://192.168.57.77:81/app_dev.php/saml/sp/acs',
          'index' => 0,
        ),
        1 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => 'http://192.168.57.77:81/app_dev.php/saml/sp/acs',
          'index' => 1,
        ),
      ),
      'SingleLogoutService' => 
      array (
        0 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect',
          'Location' => 'http://192.168.57.77:81/app_dev.php/saml/sp/logout',
        ),
        1 => 
        array (
          'Binding' => 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST',
          'Location' => 'http://192.168.57.77:81/app_dev.php/saml/sp/logout',
        ),
      ),
      'saml20.sign.assertion' => false,
    );
